name: Heroku and Docker Hub Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy
        uses: actions/checkout@v2
      - name: Push to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
 
          email: ${{ secrets.HEROKU_EMAIL }}
          
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          dockerfile_directory: ./

          dockerfile_name: Dockerfile

          docker_options: "--no-cache"

          process_type: web
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push on DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: carpentho/createreactapp:latest

