name: Heroku Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "create-react-app-github"
          heroku_email: "carpentier00thomas@gmail.com"
